#!/usr/bin/env bash
# Script to install nginx on my server
sudo apt update
sudo apt install -y nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo ufw status
echo "Hello World" > /var/www/html/index.html
service nginx start
